2020-11-30 06:33:49,889 INFO    MainThread:3900785 [internal.py:wandb_internal():62] W&B internal server running at pid: 3900785
2020-11-30 06:33:49,891 DEBUG   HandlerThread:3900785 [handler.py:handle_request():54] handle_request: check_version
2020-11-30 06:33:49,891 INFO    WriterThread:3900785 [datastore.py:open_for_write():76] open: wandb/run-20201130_063345-a2a6cl9y/run-a2a6cl9y.wandb
2020-11-30 06:33:49,892 DEBUG   SenderThread:3900785 [sender.py:send():88] send: header
2020-11-30 06:33:49,892 DEBUG   SenderThread:3900785 [sender.py:send():88] send: request
2020-11-30 06:33:49,892 DEBUG   SenderThread:3900785 [sender.py:send_request():97] send_request: check_version
2020-11-30 06:33:49,894 DEBUG   Thread-4  :3900785 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2020-11-30 06:33:49,935 DEBUG   Thread-4  :3900785 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51947
2020-11-30 06:33:49,951 DEBUG   SenderThread:3900785 [sender.py:send():88] send: run
2020-11-30 06:33:49,954 DEBUG   SenderThread:3900785 [git.py:repo():30] git repository is invalid
2020-11-30 06:33:49,958 DEBUG   SenderThread:3900785 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:33:50,048 DEBUG   SenderThread:3900785 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:33:50,052 DEBUG   HandlerThread:3900785 [handler.py:handle_request():54] handle_request: run_start
2020-11-30 06:33:50,053 INFO    SenderThread:3900785 [dir_watcher.py:__init__():167] watching files in: wandb/run-20201130_063345-a2a6cl9y/files
2020-11-30 06:33:50,053 INFO    SenderThread:3900785 [sender.py:_start_run_threads():464] run started: a2a6cl9y with start time 1606718029
2020-11-30 06:33:50,053 DEBUG   SenderThread:3900785 [sender.py:send():88] send: summary
2020-11-30 06:33:50,054 INFO    SenderThread:3900785 [sender.py:_save_file():542] saving file wandb-summary.json with policy end
2020-11-30 06:33:50,560 DEBUG   HandlerThread:3900785 [git.py:repo():30] git repository is invalid
2020-11-30 06:33:50,561 WARNING HandlerThread:3900785 [meta.py:_save_code():64] unable to save code -- program entry not found
2020-11-30 06:33:50,660 DEBUG   SenderThread:3900785 [sender.py:send():88] send: files
2020-11-30 06:33:50,661 INFO    SenderThread:3900785 [sender.py:_save_file():542] saving file wandb-metadata.json with policy now
2020-11-30 06:33:50,665 DEBUG   HandlerThread:3900785 [handler.py:handle_request():54] handle_request: status
2020-11-30 06:33:50,665 DEBUG   SenderThread:3900785 [sender.py:send():88] send: request
2020-11-30 06:33:50,666 DEBUG   Thread-11 :3900785 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:33:50,666 DEBUG   SenderThread:3900785 [sender.py:send_request():97] send_request: status
2020-11-30 06:33:50,668 DEBUG   SenderThread:3900785 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:33:50,737 DEBUG   SenderThread:3900785 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:33:50,747 DEBUG   Thread-11 :3900785 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-30 06:33:50,751 DEBUG   Thread-11 :3900785 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-30 06:33:50,959 DEBUG   Thread-11 :3900785 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/whitera2bit/dl_hse_gan/a2a6cl9y/wandb-metadata.json?Expires=1606804430&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=brHLLR9dON47y7sSmOqyk%2FQrNnwUzLZu8HpbMHNyo%2F7cS7R6qf%2FlNn5so5tCMJq39XrOxlYZA8qfaZ1tcJHDe1P4n%2Fyqt5DlOzz%2FYx7CZuXXfbOUKZ%2B%2Fn1%2BikdaYg4VstPffh4JJXmEXJONNfi7f0UaE63GfoB8QmOTjZtdsaOaaJae4MGxLgHG0fUuqJJCbJMwn6wXzALhFaxFrIAbYHyy60IvwvuQAtj%2FuWuNhuuodHdmAs03bf08oML1NRc18NsXYmyzwrqWcWgldlpXa%2FxxVfdEEOXBkryC7r2t08wjKoQKEAdKCTUMlcKNM84VyLtgCGLNvkX58%2FRsEyuuPSA%3D%3D HTTP/1.1" 200 0
2020-11-30 06:33:50,961 INFO    Thread-11 :3900785 [upload_job.py:push():112] Uploaded file /tmp/tmpss9b9fx5wandb/14tvp8cm-wandb-metadata.json
2020-11-30 06:33:51,054 INFO    Thread-8  :3900785 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063345-a2a6cl9y/files/wandb-metadata.json
2020-11-30 06:33:51,055 INFO    Thread-8  :3900785 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063345-a2a6cl9y/files/wandb-summary.json
2020-11-30 06:33:51,055 INFO    Thread-8  :3900785 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063345-a2a6cl9y/files/requirements.txt
2020-11-30 06:33:51,055 INFO    Thread-8  :3900785 [dir_watcher.py:_on_file_created():215] file/dir created: wandb/run-20201130_063345-a2a6cl9y/files/output.log
2020-11-30 06:33:52,055 DEBUG   Thread-5  :3900785 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-30 06:33:52,131 DEBUG   Thread-5  :3900785 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/whitera2bit/dl_hse_gan/a2a6cl9y/file_stream HTTP/1.1" 200 None
